"""add watch_logs table

Revision ID: 8bf87baf241d
Revises: ea5597bab117
Create Date: 2026-09-07 10:28:24.069049+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf87baf241d'
down_revision: Union[str, None] = 'ea5597bab117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.String(length=100), nullable=False),
    sa.Column('showing_id', sa.Integer(), nullable=True),
    sa.Column('watched_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 0.5 AND rating <= 5.0)', name='ck_watch_log_rating_range'),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['showing_id'], ['showings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'showing_id', name='uq_user_showing')
    )
    op.create_index(op.f('ix_watch_logs_film_id'), 'watch_logs', ['film_id'], unique=False)
    op.create_index(op.f('ix_watch_logs_showing_id'), 'watch_logs', ['showing_id'], unique=False)
    op.create_index(op.f('ix_watch_logs_user_id'), 'watch_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_watch_logs_watched_date'), 'watch_logs', ['watched_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watch_logs_watched_date'), table_name='watch_logs')
    op.drop_index(op.f('ix_watch_logs_user_id'), table_name='watch_logs')
    op.drop_index(op.f('ix_watch_logs_showing_id'), table_name='watch_logs')
    op.drop_index(op.f('ix_watch_logs_film_id'), table_name='watch_logs')
    op.drop_table('watch_logs')
    # ### end Alembic commands ###
